import { describe, expect, test } from "vitest";

import {
  normalizeAmbientTypeFields,
  compareTypeArtifacts,
} from "../../../scripts/check-types-drift.mjs";

// A committed artifact and a freshly generated one that differ ONLY in
// `PostgrestVersion`. That field reports the hosted Supabase project's
// PostgREST deployment, not the schema, so the platform can change it with
// no code change on our side. The drift gate exists to catch SCHEMA drift;
// treating an ambient platform value as drift reddens CI on every branch at
// once for a reason no branch author can act on.
const committed = `// Generated by \`supabase gen types typescript\`.
export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.17"
  }
  public: {
    Tables: {
      wines: { Row: { id: string; status: "pending" | "applied" } }
    }
  }
}
`;

const ambientOnly = committed.replace('"14.17"', '"14.5"');

const schemaChanged = committed.replace(
  "wines: { Row: { id: string; status: \"pending\" | \"applied\" } }",
  "wines: { Row: { id: string; lwin_id: string; status: \"pending\" | \"applied\" } }",
);

// The regression that a too-greedy normalizer hides: an enum member RENAMED,
// leaving the same number of quoted literals in the same positions. Blanking
// every quoted string makes this artifact identical to the committed one, so
// the gate would wave a real schema change straight through.
const enumValueRenamed = committed.replace('"applied"', '"reverted"');

const bothChanged = schemaChanged.replace('"14.17"', '"14.5"');

describe("types drift gate", () => {
  test("normalization erases the ambient PostgrestVersion but nothing else", () => {
    expect(normalizeAmbientTypeFields(committed)).toBe(
      normalizeAmbientTypeFields(ambientOnly),
    );
    // The rest of the artifact must survive normalization verbatim, or the
    // gate would be blind to real changes near the normalized line.
    expect(normalizeAmbientTypeFields(committed)).toContain(
      'status: "pending" | "applied"',
    );
    expect(normalizeAmbientTypeFields(committed)).not.toContain("14.17");
  });

  test("a PostgrestVersion-only difference is NOT drift", () => {
    expect(compareTypeArtifacts(committed, ambientOnly).drifted).toBe(false);
  });

  test("a schema difference IS drift", () => {
    const result = compareTypeArtifacts(committed, schemaChanged);
    expect(result.drifted).toBe(true);
    expect(result.diff).toContain("lwin_id");
  });

  test("a schema difference is still drift when the ambient value also moved", () => {
    // The dangerous regression: normalizing too greedily (or bailing out as
    // soon as the version differs) would let a real schema change ride in
    // behind a platform version bump.
    expect(compareTypeArtifacts(committed, bothChanged).drifted).toBe(true);
  });

  test("a renamed enum member IS drift", () => {
    // Guards against normalizing quoted literals wholesale.
    expect(compareTypeArtifacts(committed, enumValueRenamed).drifted).toBe(
      true,
    );
  });

  test("identical artifacts are not drift", () => {
    expect(compareTypeArtifacts(committed, committed).drifted).toBe(false);
  });
});
