// Generated by `supabase gen types typescript` via the Supabase MCP.
// Re-run after every migration. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      cellar_config: {
        Row: {
          id: string
          restaurant_id: string
          name: string
          rows: number
          columns: number
          labels: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          name?: string
          rows?: number
          columns?: number
          labels?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          name?: string
          rows?: number
          columns?: number
          labels?: Json
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cellar_config_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_items: {
        Row: {
          added_at: string
          added_via: Database["public"]["Enums"]["added_via"]
          bin_location: string | null
          id: string
          invoice_scan_id: string | null
          quantity: number
          restaurant_id: string
          unit_cost: number
          updated_at: string
          wine_id: string
        }
        Insert: {
          added_at?: string
          added_via?: Database["public"]["Enums"]["added_via"]
          bin_location?: string | null
          id?: string
          invoice_scan_id?: string | null
          quantity: number
          restaurant_id: string
          unit_cost: number
          updated_at?: string
          wine_id: string
        }
        Update: {
          added_at?: string
          added_via?: Database["public"]["Enums"]["added_via"]
          bin_location?: string | null
          id?: string
          invoice_scan_id?: string | null
          quantity?: number
          restaurant_id?: string
          unit_cost?: number
          updated_at?: string
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_invoice_scan_id_fkey"
            columns: ["invoice_scan_id"]
            isOneToOne: false
            referencedRelation: "invoice_scans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_wine_id_fkey"
            columns: ["wine_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          id: string
          restaurant_id: string
          email: string | null
          role: Database["public"]["Enums"]["membership_role"]
          invited_by: string
          token: string
          expires_at: string
          accepted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          email?: string | null
          role?: Database["public"]["Enums"]["membership_role"]
          invited_by: string
          token?: string
          expires_at?: string
          accepted_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          email?: string | null
          role?: Database["public"]["Enums"]["membership_role"]
          invited_by?: string
          token?: string
          expires_at?: string
          accepted_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      invoice_scans: {
        Row: {
          accuracy_score: number | null
          created_at: string
          distributor_name: string
          edits: Json
          final_line_items: Json
          id: string
          invoice_date: string | null
          invoice_number: string | null
          item_count: number
          parsed_line_items: Json
          raw_image_path: string | null
          restaurant_id: string
        }
        Insert: {
          accuracy_score?: number | null
          created_at?: string
          distributor_name: string
          edits?: Json
          final_line_items: Json
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          item_count?: number
          parsed_line_items: Json
          raw_image_path?: string | null
          restaurant_id: string
        }
        Update: {
          accuracy_score?: number | null
          created_at?: string
          distributor_name?: string
          edits?: Json
          final_line_items?: Json
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          item_count?: number
          parsed_line_items?: Json
          raw_image_path?: string | null
          restaurant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoice_scans_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      lwin_catalog: {
        Row: {
          lwin_id: string
          display_name: string
          producer: string | null
          varietal: string | null
          region: string | null
          country: string | null
          colour: string | null
          type: string | null
        }
        Insert: {
          lwin_id: string
          display_name: string
          producer?: string | null
          varietal?: string | null
          region?: string | null
          country?: string | null
          colour?: string | null
          type?: string | null
        }
        Update: {
          lwin_id?: string
          display_name?: string
          producer?: string | null
          varietal?: string | null
          region?: string | null
          country?: string | null
          colour?: string | null
          type?: string | null
        }
        Relationships: []
      }
      memberships: {
        Row: {
          created_at: string
          id: string
          restaurant_id: string
          role: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          restaurant_id: string
          role?: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          restaurant_id?: string
          role?: Database["public"]["Enums"]["membership_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurants: {
        Row: {
          created_at: string
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      wine_list_items: {
        Row: {
          bottle_price: number | null
          created_at: string
          glass_price: number | null
          id: string
          is_available: boolean
          position: number
          section_id: string
          tasting_note: string | null
          updated_at: string
          wine_id: string
        }
        Insert: {
          bottle_price?: number | null
          created_at?: string
          glass_price?: number | null
          id?: string
          is_available?: boolean
          position?: number
          section_id: string
          tasting_note?: string | null
          updated_at?: string
          wine_id: string
        }
        Update: {
          bottle_price?: number | null
          created_at?: string
          glass_price?: number | null
          id?: string
          is_available?: boolean
          position?: number
          section_id?: string
          tasting_note?: string | null
          updated_at?: string
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_list_items_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "wine_list_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wine_list_items_wine_id_fkey"
            columns: ["wine_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id"]
          },
        ]
      }
      wine_list_sections: {
        Row: {
          created_at: string
          id: string
          name: string
          position: number
          wine_list_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          position?: number
          wine_list_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          position?: number
          wine_list_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_list_sections_wine_list_id_fkey"
            columns: ["wine_list_id"]
            isOneToOne: false
            referencedRelation: "wine_lists"
            referencedColumns: ["id"]
          },
        ]
      }
      wine_lists: {
        Row: {
          created_at: string
          id: string
          is_published: boolean
          last_published_at: string | null
          name: string
          restaurant_id: string
          slug: string | null
          template: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_published?: boolean
          last_published_at?: string | null
          name: string
          restaurant_id: string
          slug?: string | null
          template?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_published?: boolean
          last_published_at?: string | null
          name?: string
          restaurant_id?: string
          slug?: string | null
          template?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_lists_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      wines: {
        Row: {
          country: string | null
          created_at: string
          drink_window_start: number | null
          drink_window_end: number | null
          id: string
          lwin_id: string | null
          name: string
          producer: string
          region: string | null
          restaurant_id: string
          serving_temp_min: number | null
          serving_temp_max: number | null
          serving_temp_label: string | null
          size_ml: number
          updated_at: string
          varietal: string | null
          vintage: number | null
        }
        Insert: {
          country?: string | null
          created_at?: string
          drink_window_start?: number | null
          drink_window_end?: number | null
          id?: string
          lwin_id?: string | null
          name: string
          producer: string
          region?: string | null
          restaurant_id: string
          serving_temp_min?: number | null
          serving_temp_max?: number | null
          serving_temp_label?: string | null
          size_ml?: number
          updated_at?: string
          varietal?: string | null
          vintage?: number | null
        }
        Update: {
          country?: string | null
          created_at?: string
          drink_window_start?: number | null
          drink_window_end?: number | null
          id?: string
          lwin_id?: string | null
          name?: string
          producer?: string
          region?: string | null
          restaurant_id?: string
          serving_temp_min?: number | null
          serving_temp_max?: number | null
          serving_temp_label?: string | null
          size_ml?: number
          updated_at?: string
          varietal?: string | null
          vintage?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "wines_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      find_or_create_wine: {
        Args: {
          p_country?: string
          p_name: string
          p_producer: string
          p_region?: string
          p_restaurant_id: string
          p_size_ml?: number
          p_varietal?: string
          p_vintage?: number
        }
        Returns: string
      }
      generate_slug: { Args: { input: string }; Returns: string }
      is_member: { Args: { r_id: string }; Returns: boolean }
      is_member_with_role: {
        Args: {
          r_id: string
          required: Database["public"]["Enums"]["membership_role"]
        }
        Returns: boolean
      }
    }
    Enums: {
      added_via: "manual" | "invoice_scan"
      membership_role: "owner" | "manager" | "staff"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      added_via: ["manual", "invoice_scan"],
      membership_role: ["owner", "manager", "staff"],
    },
  },
} as const
