// Generated by `supabase gen types typescript` via the Supabase MCP.
// Re-run after every migration. Do not edit by hand.
//
// Regeneration: `pnpm run types:gen` (requires SUPABASE_ACCESS_TOKEN +
// SUPABASE_PROJECT_ID env). CI verifies this file matches the live
// schema via `pnpm run types:check`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      api_idempotency: {
        Row: {
          completed_at: string | null
          created_at: string
          idempotency_key: string
          operation_id: string
          request_hash: string
          response_body: Json | null
          response_headers: Json | null
          response_status: number | null
          restaurant_id: string
          state: string
          updated_at: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          idempotency_key: string
          operation_id: string
          request_hash: string
          response_body?: Json | null
          response_headers?: Json | null
          response_status?: number | null
          restaurant_id: string
          state?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          idempotency_key?: string
          operation_id?: string
          request_hash?: string
          response_body?: Json | null
          response_headers?: Json | null
          response_status?: number | null
          restaurant_id?: string
          state?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "api_idempotency_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      api_rate_limit_buckets: {
        Row: {
          bucket_key: string
          created_at: string
          request_count: number
          reset_at: string
          updated_at: string
          user_id: string
          window_seconds: number
          window_start: string
        }
        Insert: {
          bucket_key: string
          created_at?: string
          request_count: number
          reset_at: string
          updated_at?: string
          user_id: string
          window_seconds: number
          window_start: string
        }
        Update: {
          bucket_key?: string
          created_at?: string
          request_count?: number
          reset_at?: string
          updated_at?: string
          user_id?: string
          window_seconds?: number
          window_start?: string
        }
        Relationships: []
      }
      availability_events: {
        Row: {
          created_at: string
          delta: number | null
          direction: string
          id: string
          note: string | null
          restaurant_id: string
          user_id: string | null
          wine_id: string
        }
        Insert: {
          created_at?: string
          delta?: number | null
          direction: string
          id?: string
          note?: string | null
          restaurant_id: string
          user_id?: string | null
          wine_id: string
        }
        Update: {
          created_at?: string
          delta?: number | null
          direction?: string
          id?: string
          note?: string | null
          restaurant_id?: string
          user_id?: string | null
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "availability_events_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "availability_events_wine_tenant_fkey"
            columns: ["wine_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id", "restaurant_id"]
          },
        ]
      }
      background_jobs: {
        Row: {
          attempt_count: number
          created_at: string
          created_by: string | null
          error_code: string | null
          error_message: string | null
          finished_at: string | null
          id: string
          job_type: string
          max_attempts: number
          metadata: Json
          restaurant_id: string
          result: Json
          run_after: string
          started_at: string | null
          status: string
          subject_id: string | null
          subject_table: string | null
          updated_at: string
        }
        Insert: {
          attempt_count?: number
          created_at?: string
          created_by?: string | null
          error_code?: string | null
          error_message?: string | null
          finished_at?: string | null
          id?: string
          job_type: string
          max_attempts?: number
          metadata?: Json
          restaurant_id: string
          result?: Json
          run_after?: string
          started_at?: string | null
          status?: string
          subject_id?: string | null
          subject_table?: string | null
          updated_at?: string
        }
        Update: {
          attempt_count?: number
          created_at?: string
          created_by?: string | null
          error_code?: string | null
          error_message?: string | null
          finished_at?: string | null
          id?: string
          job_type?: string
          max_attempts?: number
          metadata?: Json
          restaurant_id?: string
          result?: Json
          run_after?: string
          started_at?: string | null
          status?: string
          subject_id?: string | null
          subject_table?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "background_jobs_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      cellar_config: {
        Row: {
          columns: number
          created_at: string
          id: string
          labels: Json
          low_stock_threshold: number
          name: string
          reconcile_variance_threshold_oz: number
          restaurant_id: string
          rows: number
          updated_at: string
        }
        Insert: {
          columns?: number
          created_at?: string
          id?: string
          labels?: Json
          low_stock_threshold?: number
          name?: string
          reconcile_variance_threshold_oz?: number
          restaurant_id: string
          rows?: number
          updated_at?: string
        }
        Update: {
          columns?: number
          created_at?: string
          id?: string
          labels?: Json
          low_stock_threshold?: number
          name?: string
          reconcile_variance_threshold_oz?: number
          restaurant_id?: string
          rows?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cellar_config_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory_items: {
        Row: {
          added_at: string
          added_via: Database["public"]["Enums"]["added_via"]
          bin_location: string | null
          currency: string | null
          format: string | null
          id: string
          invoice_scan_id: string | null
          quantity: number
          restaurant_id: string
          section: string | null
          unit_cost: number
          updated_at: string
          wine_id: string
        }
        Insert: {
          added_at?: string
          added_via?: Database["public"]["Enums"]["added_via"]
          bin_location?: string | null
          currency?: string | null
          format?: string | null
          id?: string
          invoice_scan_id?: string | null
          quantity: number
          restaurant_id: string
          section?: string | null
          unit_cost: number
          updated_at?: string
          wine_id: string
        }
        Update: {
          added_at?: string
          added_via?: Database["public"]["Enums"]["added_via"]
          bin_location?: string | null
          currency?: string | null
          format?: string | null
          id?: string
          invoice_scan_id?: string | null
          quantity?: number
          restaurant_id?: string
          section?: string | null
          unit_cost?: number
          updated_at?: string
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_items_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_items_scan_tenant_fkey"
            columns: ["invoice_scan_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "invoice_scans"
            referencedColumns: ["id", "restaurant_id"]
          },
          {
            foreignKeyName: "inventory_items_wine_tenant_fkey"
            columns: ["wine_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id", "restaurant_id"]
          },
        ]
      }
      invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string
          restaurant_id: string
          role: Database["public"]["Enums"]["membership_role"]
          token: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by: string
          restaurant_id: string
          role?: Database["public"]["Enums"]["membership_role"]
          token?: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string
          restaurant_id?: string
          role?: Database["public"]["Enums"]["membership_role"]
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      invoice_scans: {
        Row: {
          accuracy_score: number | null
          created_at: string
          created_by: string | null
          distributor_name: string
          edits: Json
          extra_image_paths: Json
          final_line_items: Json
          id: string
          invoice_date: string | null
          invoice_number: string | null
          item_count: number
          ocr_text: Json | null
          parsed_line_items: Json
          raw_image_path: string | null
          restaurant_id: string
          status: string
        }
        Insert: {
          accuracy_score?: number | null
          created_at?: string
          created_by?: string | null
          distributor_name: string
          edits?: Json
          extra_image_paths?: Json
          final_line_items: Json
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          item_count?: number
          ocr_text?: Json | null
          parsed_line_items: Json
          raw_image_path?: string | null
          restaurant_id: string
          status?: string
        }
        Update: {
          accuracy_score?: number | null
          created_at?: string
          created_by?: string | null
          distributor_name?: string
          edits?: Json
          extra_image_paths?: Json
          final_line_items?: Json
          id?: string
          invoice_date?: string | null
          invoice_number?: string | null
          item_count?: number
          ocr_text?: Json | null
          parsed_line_items?: Json
          raw_image_path?: string | null
          restaurant_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "invoice_scans_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      lwin_catalog: {
        Row: {
          colour: string | null
          country: string | null
          display_name: string
          lwin_id: string
          producer: string | null
          region: string | null
          type: string | null
          varietal: string | null
        }
        Insert: {
          colour?: string | null
          country?: string | null
          display_name: string
          lwin_id: string
          producer?: string | null
          region?: string | null
          type?: string | null
          varietal?: string | null
        }
        Update: {
          colour?: string | null
          country?: string | null
          display_name?: string
          lwin_id?: string
          producer?: string | null
          region?: string | null
          type?: string | null
          varietal?: string | null
        }
        Relationships: []
      }
      memberships: {
        Row: {
          created_at: string
          id: string
          restaurant_id: string
          role: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          restaurant_id: string
          role?: Database["public"]["Enums"]["membership_role"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          restaurant_id?: string
          role?: Database["public"]["Enums"]["membership_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      open_bottles: {
        Row: {
          closed_at: string | null
          id: string
          opened_at: string
          opened_by: string | null
          remaining_ml: number
          restaurant_id: string
          source_inventory_item_id: string | null
          wine_id: string
        }
        Insert: {
          closed_at?: string | null
          id?: string
          opened_at?: string
          opened_by?: string | null
          remaining_ml: number
          restaurant_id: string
          source_inventory_item_id?: string | null
          wine_id: string
        }
        Update: {
          closed_at?: string | null
          id?: string
          opened_at?: string
          opened_by?: string | null
          remaining_ml?: number
          restaurant_id?: string
          source_inventory_item_id?: string | null
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "open_bottles_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "open_bottles_source_inventory_tenant_fkey"
            columns: ["source_inventory_item_id", "wine_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "inventory_items"
            referencedColumns: ["id", "wine_id", "restaurant_id"]
          },
          {
            foreignKeyName: "open_bottles_wine_tenant_fkey"
            columns: ["wine_id", "restaurant_id"]
            isOneToOne: true
            referencedRelation: "wines"
            referencedColumns: ["id", "restaurant_id"]
          },
        ]
      }
      pour_events: {
        Row: {
          actor_user_id: string | null
          id: string
          kind: string
          ml_delta: number
          note: string | null
          occurred_at: string
          open_bottle_id: string | null
          restaurant_id: string
          wine_id: string
        }
        Insert: {
          actor_user_id?: string | null
          id?: string
          kind: string
          ml_delta: number
          note?: string | null
          occurred_at?: string
          open_bottle_id?: string | null
          restaurant_id: string
          wine_id: string
        }
        Update: {
          actor_user_id?: string | null
          id?: string
          kind?: string
          ml_delta?: number
          note?: string | null
          occurred_at?: string
          open_bottle_id?: string | null
          restaurant_id?: string
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pour_events_open_bottle_tenant_fkey"
            columns: ["open_bottle_id", "wine_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "open_bottles"
            referencedColumns: ["id", "wine_id", "restaurant_id"]
          },
          {
            foreignKeyName: "pour_events_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pour_events_wine_tenant_fkey"
            columns: ["wine_id", "restaurant_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id", "restaurant_id"]
          },
        ]
      }
      restaurants: {
        Row: {
          auto_eightysix_from_inventory: boolean
          created_at: string
          default_target_markup_ratio: number | null
          default_target_pour_cost_pct: number | null
          eightysix_ml_threshold: number
          eightysix_strategy: string
          id: string
          logo_url: string | null
          name: string
          updated_at: string
        }
        Insert: {
          auto_eightysix_from_inventory?: boolean
          created_at?: string
          default_target_markup_ratio?: number | null
          default_target_pour_cost_pct?: number | null
          eightysix_ml_threshold?: number
          eightysix_strategy?: string
          id?: string
          logo_url?: string | null
          name?: string
          updated_at?: string
        }
        Update: {
          auto_eightysix_from_inventory?: boolean
          created_at?: string
          default_target_markup_ratio?: number | null
          default_target_pour_cost_pct?: number | null
          eightysix_ml_threshold?: number
          eightysix_strategy?: string
          id?: string
          logo_url?: string | null
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      scan_idempotency: {
        Row: {
          created_at: string
          key: string
          response_body: Json | null
          response_status: number | null
          restaurant_id: string
        }
        Insert: {
          created_at?: string
          key: string
          response_body?: Json | null
          response_status?: number | null
          restaurant_id: string
        }
        Update: {
          created_at?: string
          key?: string
          response_body?: Json | null
          response_status?: number | null
          restaurant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "scan_idempotency_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      wine_list_items: {
        Row: {
          blurb: string | null
          bottle_price: number | null
          created_at: string
          glass_pour_ml: number | null
          glass_price: number | null
          hidden: boolean
          id: string
          is_available: boolean
          name_override: string | null
          position: number
          pour_size_mode: string
          section_id: string
          tasting_note: string | null
          updated_at: string
          wine_id: string
        }
        Insert: {
          blurb?: string | null
          bottle_price?: number | null
          created_at?: string
          glass_pour_ml?: number | null
          glass_price?: number | null
          hidden?: boolean
          id?: string
          is_available?: boolean
          name_override?: string | null
          position?: number
          pour_size_mode?: string
          section_id: string
          tasting_note?: string | null
          updated_at?: string
          wine_id: string
        }
        Update: {
          blurb?: string | null
          bottle_price?: number | null
          created_at?: string
          glass_pour_ml?: number | null
          glass_price?: number | null
          hidden?: boolean
          id?: string
          is_available?: boolean
          name_override?: string | null
          position?: number
          pour_size_mode?: string
          section_id?: string
          tasting_note?: string | null
          updated_at?: string
          wine_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_list_items_section_id_fkey"
            columns: ["section_id"]
            isOneToOne: false
            referencedRelation: "wine_list_sections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wine_list_items_wine_id_fkey"
            columns: ["wine_id"]
            isOneToOne: false
            referencedRelation: "wines"
            referencedColumns: ["id"]
          },
        ]
      }
      wine_list_sections: {
        Row: {
          created_at: string
          id: string
          name: string
          position: number
          wine_list_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          position?: number
          wine_list_id: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          position?: number
          wine_list_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_list_sections_wine_list_id_fkey"
            columns: ["wine_list_id"]
            isOneToOne: false
            referencedRelation: "wine_lists"
            referencedColumns: ["id"]
          },
        ]
      }
      wine_lists: {
        Row: {
          archived: boolean
          created_at: string
          description: string | null
          id: string
          is_published: boolean
          last_published_at: string | null
          name: string
          restaurant_id: string
          slug: string | null
          template: string
          updated_at: string
        }
        Insert: {
          archived?: boolean
          created_at?: string
          description?: string | null
          id?: string
          is_published?: boolean
          last_published_at?: string | null
          name: string
          restaurant_id: string
          slug?: string | null
          template?: string
          updated_at?: string
        }
        Update: {
          archived?: boolean
          created_at?: string
          description?: string | null
          id?: string
          is_published?: boolean
          last_published_at?: string | null
          name?: string
          restaurant_id?: string
          slug?: string | null
          template?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "wine_lists_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      wines: {
        Row: {
          alert_snoozed_until: string | null
          colour: string | null
          country: string | null
          created_at: string
          decant_minutes: number | null
          drink_window_end: number | null
          drink_window_start: number | null
          eightysixed_at: string | null
          eightysixed_by: string | null
          enrichment_metadata: Json | null
          hero_image_url: string | null
          id: string
          is_eightysixed: boolean
          last_enriched_at: string | null
          lwin_id: string | null
          manual_overrides: string[] | null
          name: string
          overpaid_flag: boolean
          peak_year: number | null
          pricing_dismissed_until: string | null
          pricing_target_markup_ratio: number | null
          pricing_target_pour_cost_pct: number | null
          producer: string
          rating: number | null
          rating_source: string | null
          region: string | null
          restaurant_id: string
          retail_max: number | null
          retail_median: number | null
          retail_min: number | null
          retail_refreshed_at: string | null
          retail_retailer_count: number | null
          review_excerpt: string | null
          serving_temp_label: string | null
          serving_temp_max: number | null
          serving_temp_min: number | null
          size_ml: number
          tasting_notes: string | null
          updated_at: string
          varietal: string | null
          vintage: number | null
        }
        Insert: {
          alert_snoozed_until?: string | null
          colour?: string | null
          country?: string | null
          created_at?: string
          decant_minutes?: number | null
          drink_window_end?: number | null
          drink_window_start?: number | null
          eightysixed_at?: string | null
          eightysixed_by?: string | null
          enrichment_metadata?: Json | null
          hero_image_url?: string | null
          id?: string
          is_eightysixed?: boolean
          last_enriched_at?: string | null
          lwin_id?: string | null
          manual_overrides?: string[] | null
          name: string
          overpaid_flag?: boolean
          peak_year?: number | null
          pricing_dismissed_until?: string | null
          pricing_target_markup_ratio?: number | null
          pricing_target_pour_cost_pct?: number | null
          producer: string
          rating?: number | null
          rating_source?: string | null
          region?: string | null
          restaurant_id: string
          retail_max?: number | null
          retail_median?: number | null
          retail_min?: number | null
          retail_refreshed_at?: string | null
          retail_retailer_count?: number | null
          review_excerpt?: string | null
          serving_temp_label?: string | null
          serving_temp_max?: number | null
          serving_temp_min?: number | null
          size_ml?: number
          tasting_notes?: string | null
          updated_at?: string
          varietal?: string | null
          vintage?: number | null
        }
        Update: {
          alert_snoozed_until?: string | null
          colour?: string | null
          country?: string | null
          created_at?: string
          decant_minutes?: number | null
          drink_window_end?: number | null
          drink_window_start?: number | null
          eightysixed_at?: string | null
          eightysixed_by?: string | null
          enrichment_metadata?: Json | null
          hero_image_url?: string | null
          id?: string
          is_eightysixed?: boolean
          last_enriched_at?: string | null
          lwin_id?: string | null
          manual_overrides?: string[] | null
          name?: string
          overpaid_flag?: boolean
          peak_year?: number | null
          pricing_dismissed_until?: string | null
          pricing_target_markup_ratio?: number | null
          pricing_target_pour_cost_pct?: number | null
          producer?: string
          rating?: number | null
          rating_source?: string | null
          region?: string | null
          restaurant_id?: string
          retail_max?: number | null
          retail_median?: number | null
          retail_min?: number | null
          retail_refreshed_at?: string | null
          retail_retailer_count?: number | null
          review_excerpt?: string | null
          serving_temp_label?: string | null
          serving_temp_max?: number | null
          serving_temp_min?: number | null
          size_ml?: number
          tasting_notes?: string | null
          updated_at?: string
          varietal?: string | null
          vintage?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "wines_restaurant_id_fkey"
            columns: ["restaurant_id"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invitation_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_request_hash?: string
          p_token: string
        }
        Returns: {
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      add_manual_overrides: {
        Args: { p_fields: string[]; p_wine_id: string }
        Returns: undefined
      }
      assign_cellar_section_batch: {
        Args: {
          p_restaurant_id: string
          p_section: string
          p_wine_ids: string[]
        }
        Returns: undefined
      }
      cellar_inventory_wine_ids: {
        Args: { p_restaurant_id: string; p_wine_ids: string[] }
        Returns: string[]
      }
      claim_api_idempotency: {
        Args: {
          p_idempotency_key: string
          p_operation_id: string
          p_request_hash: string
          p_restaurant_id: string
        }
        Returns: {
          outcome: string
          response_body: Json
          response_headers: Json
          response_status: number
        }[]
      }
      cleanup_api_idempotency: { Args: never; Returns: number }
      cleanup_api_rate_limit_buckets: { Args: never; Returns: number }
      cleanup_scan_idempotency: { Args: never; Returns: undefined }
      close_open_bottle_idempotent: {
        Args: {
          p_bottle_id: string
          p_expected_opened_at: string
          p_idempotency_key?: string
          p_request_hash?: string
          p_restaurant_id: string
        }
        Returns: {
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      complete_api_idempotency: {
        Args: {
          p_idempotency_key: string
          p_operation_id: string
          p_request_hash: string
          p_response_body: Json
          p_response_headers: Json
          p_response_status: number
          p_restaurant_id: string
        }
        Returns: boolean
      }
      consume_api_rate_limit: {
        Args: { p_risk_class: string }
        Returns: {
          allowed: boolean
          limit_count: number
          remaining: number
          reset_at: string
          retry_after_seconds: number
        }[]
      }
      create_wine_list_item_idempotent: {
        Args: {
          p_bottle_price?: number
          p_glass_price?: number
          p_idempotency_key?: string
          p_name_override?: string
          p_request_hash?: string
          p_restaurant_id: string
          p_section_id: string
          p_wine_id: string
        }
        Returns: {
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      dismiss_pricing_alert: {
        Args: { p_days?: number; p_wine_id: string }
        Returns: string
      }
      enrich_wines_batch: {
        Args: { p_enrichments: Json; p_restaurant_id: string }
        Returns: number
      }
      fail_api_idempotency: {
        Args: {
          p_idempotency_key: string
          p_operation_id: string
          p_request_hash: string
          p_restaurant_id: string
        }
        Returns: boolean
      }
      find_or_create_wine: {
        Args: {
          p_country?: string
          p_name: string
          p_producer: string
          p_region?: string
          p_restaurant_id: string
          p_size_ml?: number
          p_varietal?: string
          p_vintage?: number
        }
        Returns: string
      }
      find_or_create_wines_batch: {
        Args: { p_restaurant_id: string; p_wines: Json }
        Returns: string[]
      }
      generate_slug: { Args: { input: string }; Returns: string }
      is_member: { Args: { r_id: string }; Returns: boolean }
      is_member_with_role: {
        Args: {
          r_id: string
          required: Database["public"]["Enums"]["membership_role"]
        }
        Returns: boolean
      }
      list_open_bottle_items: {
        Args: { p_restaurant_id: string }
        Returns: {
          glass_pour_ml: number
          name: string
          open_remaining_ml: number
          opened_at: string
          pour_size_mode: string
          producer: string
          sealed_count: number
          size_ml: number
          vintage: number
          wine_id: string
          wine_list_item_id: string
        }[]
      }
      lwin_search: {
        Args: { p_limit?: number; p_query: string }
        Returns: {
          colour: string | null
          country: string | null
          display_name: string
          lwin_id: string
          producer: string | null
          region: string | null
          type: string | null
          varietal: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "lwin_catalog"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      match_lwin: {
        Args: { p_name: string; p_producer: string; p_threshold?: number }
        Returns: {
          colour: string
          country: string
          display_name: string
          lwin_id: string
          producer: string
          region: string
          score: number
          varietal: string
        }[]
      }
      match_lwin_batch: {
        Args: { p_restaurant_id: string; p_wine_ids: string[] }
        Returns: {
          lwin_id: string
          score: number
          wine_id: string
        }[]
      }
      open_bottle_from_inventory: {
        Args: { p_restaurant_id: string; p_wine_id: string }
        Returns: {
          bottle_id: string
          opened_at: string
          outcome: string
          remaining_ml: number
          wine_id: string
        }[]
      }
      open_bottle_from_inventory_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_request_hash?: string
          p_restaurant_id: string
          p_wine_id: string
        }
        Returns: {
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      reconcile_open_bottle: {
        Args: {
          p_new_remaining_ml: number
          p_note?: string
          p_restaurant_id: string
          p_wine_id: string
        }
        Returns: {
          closed_at: string | null
          id: string
          opened_at: string
          opened_by: string | null
          remaining_ml: number
          restaurant_id: string
          source_inventory_item_id: string | null
          wine_id: string
        }
        SetofOptions: {
          from: "*"
          to: "open_bottles"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      reconcile_open_bottles_batch: {
        Args: { p_entries: Json; p_restaurant_id: string }
        Returns: number
      }
      reconcile_open_bottles_idempotent: {
        Args: {
          p_entries: Json
          p_idempotency_key?: string
          p_request_hash?: string
          p_restaurant_id: string
        }
        Returns: {
          execution_started_at: string
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      record_pour: {
        Args: {
          p_kind?: string
          p_ml: number
          p_note?: string
          p_restaurant_id: string
          p_wine_id: string
        }
        Returns: {
          closed_at: string | null
          id: string
          opened_at: string
          opened_by: string | null
          remaining_ml: number
          restaurant_id: string
          source_inventory_item_id: string | null
          wine_id: string
        }
        SetofOptions: {
          from: "*"
          to: "open_bottles"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      record_pour_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_kind?: string
          p_ml: number
          p_note?: string
          p_request_hash?: string
          p_restaurant_id: string
          p_wine_id: string
        }
        Returns: {
          execution_started_at: string
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      release_api_idempotency: {
        Args: {
          p_idempotency_key: string
          p_operation_id: string
          p_request_hash: string
          p_restaurant_id: string
        }
        Returns: boolean
      }
      remove_team_member_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_member_id: string
          p_request_hash?: string
          p_restaurant_id: string
        }
        Returns: {
          execution_started_at: string
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      reorder_wine_list_items: {
        Args: { p_ordered_ids: string[] }
        Returns: undefined
      }
      set_wine_availability: {
        Args: { p_direction: string; p_note: string; p_wine_id: string }
        Returns: {
          created_at: string
          delta: number | null
          direction: string
          id: string
          note: string | null
          restaurant_id: string
          user_id: string | null
          wine_id: string
        }[]
        SetofOptions: {
          from: "*"
          to: "availability_events"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      snooze_drink_window_alert: {
        Args: { p_days?: number; p_wine_id: string }
        Returns: string
      }
      undo_last_pour: {
        Args: { p_restaurant_id: string; p_wine_id: string }
        Returns: {
          closed_at: string | null
          id: string
          opened_at: string
          opened_by: string | null
          remaining_ml: number
          restaurant_id: string
          source_inventory_item_id: string | null
          wine_id: string
        }
        SetofOptions: {
          from: "*"
          to: "open_bottles"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      undo_last_pour_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_request_hash?: string
          p_restaurant_id: string
          p_wine_id: string
        }
        Returns: {
          execution_started_at: string
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      update_team_member_role_idempotent: {
        Args: {
          p_idempotency_key?: string
          p_member_id: string
          p_request_hash?: string
          p_restaurant_id: string
          p_role: Database["public"]["Enums"]["membership_role"]
        }
        Returns: {
          execution_started_at: string
          outcome: string
          replayed: boolean
          response_body: Json
          response_status: number
        }[]
      }
      wine_published_list_slugs: {
        Args: { p_restaurant_id: string; p_wine_id: string }
        Returns: {
          slug: string
        }[]
      }
    }
    Enums: {
      added_via: "manual" | "invoice_scan" | "bottle_scan"
      membership_role: "owner" | "manager" | "staff"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      added_via: ["manual", "invoice_scan", "bottle_scan"],
      membership_role: ["owner", "manager", "staff"],
    },
  },
} as const
