// P2 — golden-vector contract test against P1's fixture generator.
//
// docs/plans/2026-08-23-p2-identity-spine.md §5's "critical cross-piece
// fact": P1's fixture generator (scripts/fixtures/generate-partner-cellar.mjs,
// a SEPARATE worktree — terroir-vw-p1 — this P2 worktree cannot edit) has
// its own inline normalizeForDedup() used to prove its spelling-noise
// groups converge. This file imports that function AND P1's own
// generateDataset() DIRECTLY from the sibling worktree and asserts
// agreement with this worktree's normalizeProducerOrCuvee/normalizeVintage
// — not a hand-copied fixture, the actual live function.
//
// P2 ROUND-4 FIX (D8 — scratchpad db-audit/verify/P2-critic-r3.md): every
// test below that imports p1FixturePath is gated on hasP1Fixture and
// SKIPS (not fails) when the terroir-vw-p1 sibling worktree isn't present
// on disk. That means those tests protect nothing in CI, nothing once
// these worktrees are cleaned up, and nothing on any machine that isn't
// this one — a check that silently reports success by never running.
// __fixtures__/normalization-golden-vectors.json is the fix: a frozen
// (input, expected) snapshot, generated by
// scripts/generate-identity-golden-vectors.ts and committed into this
// tree, that the "golden vectors (frozen" describe block below asserts
// UNCONDITIONALLY — no skipIf, no sibling path, no environment luck. The
// live cross-worktree tests stay too, upgraded to check P1's live
// function against that SAME frozen file (not just against P2's live
// output), so a future edit on EITHER side that drifts from the frozen
// contract still fails immediately while both worktrees exist. See that
// generator script's header for why regenerating this file is a
// deliberate, coordinated contract change, never a routine refresh.
import { describe, expect, it } from "vitest";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { existsSync, readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { normalizeProducerOrCuvee, normalizeVintage, isNvVintageText } from "./normalize";

// Round-6 SQL-parity block below; see its own comment for why it exists.
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const hasLiveDb = Boolean(supabaseUrl && serviceRoleKey);

const p1FixturePath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../../terroir-vw-p1/scripts/fixtures/generate-partner-cellar.mjs",
);
const hasP1Fixture = existsSync(p1FixturePath);

type GoldenVectors = {
  producerOrCuveeVectors: { input: string; expected: string }[];
  vintageTextVectors: { input: string; expectedIsNv: boolean; outcome: "throws" | number | null }[];
};

const goldenVectorsPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "__fixtures__/normalization-golden-vectors.json",
);
const goldenVectors = JSON.parse(readFileSync(goldenVectorsPath, "utf8")) as GoldenVectors;

type P1Variant = {
  producer: string;
  name: string;
  vintage: number | null;
  sizeMl: number;
  altSpelling?: { producer: string; name: string };
  tags: {
    spellingGroupId: string | null;
    spellingType: string | null;
    adjacentFamily: string | null;
    formatFamily: string | null;
  };
};

type P1DirtyRecord = {
  dirtyCategory: string;
  vintageOverride?: string;
};

type P1Module = {
  SEED: number;
  normalizeForDedup: (s: string) => string;
  generateDataset: (opts?: { seed?: number; extras?: boolean; dirty?: boolean }) => {
    variants: P1Variant[];
    dirtyRecords: P1DirtyRecord[];
  };
};

describe.skipIf(!hasP1Fixture)("golden-vector contract with P1's fixture (terroir-vw-p1)", () => {
  it("loads the sibling worktree's fixture module", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    expect(typeof mod.normalizeForDedup).toBe("function");
    expect(typeof mod.generateDataset).toBe("function");
  });

  it("all 40 SPELLING_SEEDS groups: canonical and alt forms normalize identically under BOTH P1's normalizeForDedup and P2's normalizeProducerOrCuvee", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    const { variants } = mod.generateDataset({ seed: mod.SEED });
    const spellingGroups = variants.filter((v) => v.tags.spellingGroupId !== null);

    // Sanity: the fixture really does carry all 40 dedicated groups (10
    // per category: accent_stripped, nfc_nfd, punctuation_spacing,
    // producer_reorder) — a silent drop to fewer groups would make the
    // rest of this test vacuously weaker.
    const groupIds = new Set(spellingGroups.map((v) => v.tags.spellingGroupId));
    expect(groupIds.size).toBe(40);

    for (const v of spellingGroups) {
      expect(v.altSpelling).toBeTruthy();
      const alt = v.altSpelling!;

      // P2's own function: canonical and alt forms collapse to the same
      // normalized key.
      expect(normalizeProducerOrCuvee(alt.producer)).toBe(normalizeProducerOrCuvee(v.producer));
      expect(normalizeProducerOrCuvee(alt.name)).toBe(normalizeProducerOrCuvee(v.name));

      // P1's own function, on the SAME inputs: byte-for-byte agreement
      // with P2's outputs — the actual cross-piece contract, not just
      // "both converge internally."
      expect(mod.normalizeForDedup(v.producer)).toBe(normalizeProducerOrCuvee(v.producer));
      expect(mod.normalizeForDedup(v.name)).toBe(normalizeProducerOrCuvee(v.name));
      expect(mod.normalizeForDedup(alt.producer)).toBe(normalizeProducerOrCuvee(alt.producer));
      expect(mod.normalizeForDedup(alt.name)).toBe(normalizeProducerOrCuvee(alt.name));
    }
  });

  it("normalizeVintage: exactly one (the literal \"NV\") of P1's 7 DIRTY_VINTAGE_TEXTS now passes; the other six still fail", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    const { dirtyRecords } = mod.generateDataset({ seed: mod.SEED, dirty: true });
    const dirtyVintageTexts = [
      ...new Set(
        dirtyRecords
          .filter((r) => r.dirtyCategory === "bad_vintage_text")
          .map((r) => r.vintageOverride)
          .filter((v): v is string => typeof v === "string"),
      ),
    ];

    // Sanity: the fixture really carries 7 distinct dirty vintage texts.
    expect(dirtyVintageTexts).toHaveLength(7);
    expect(dirtyVintageTexts).toContain("NV");

    const passed = dirtyVintageTexts.filter((text) => {
      try {
        return normalizeVintage(text) === null;
      } catch {
        return false;
      }
    });
    expect(passed).toEqual(["NV"]);

    const failed = dirtyVintageTexts.filter((text) => {
      try {
        normalizeVintage(text);
        return false;
      } catch {
        return true;
      }
    });
    expect(failed.sort()).toEqual(dirtyVintageTexts.filter((t) => t !== "NV").sort());
  });

  it("negative guarantee: adjacent-vintage family members share one normalized (producer,cuvee) key but keep every vintage distinct", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    const { variants } = mod.generateDataset({ seed: mod.SEED });
    const families = new Map<string, P1Variant[]>();
    for (const v of variants) {
      if (!v.tags.adjacentFamily) continue;
      const list = families.get(v.tags.adjacentFamily) ?? [];
      list.push(v);
      families.set(v.tags.adjacentFamily, list);
    }
    expect(families.size).toBeGreaterThan(0);

    for (const members of families.values()) {
      const keys = new Set(members.map((m) => `${normalizeProducerOrCuvee(m.producer)}|${normalizeProducerOrCuvee(m.name)}`));
      // Same real producer/cuvée — normalization correctly recognizes them
      // as one identity text-wise...
      expect(keys.size).toBe(1);
      // ...but vintage itself is never touched by normalization and stays
      // fully distinct per member — this, not the text key, is what keeps
      // "two genuinely different wines" (different vintages) from ever
      // colliding into one identity.
      const vintages = new Set(members.map((m) => m.vintage));
      expect(vintages.size).toBe(members.length);
    }
  });

  it("negative guarantee: format-sibling family members share one normalized (producer,cuvee) key but keep every size_ml distinct", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    const { variants } = mod.generateDataset({ seed: mod.SEED });
    const families = new Map<string, P1Variant[]>();
    for (const v of variants) {
      if (!v.tags.formatFamily) continue;
      const list = families.get(v.tags.formatFamily) ?? [];
      list.push(v);
      families.set(v.tags.formatFamily, list);
    }
    expect(families.size).toBeGreaterThan(0);

    for (const members of families.values()) {
      const keys = new Set(members.map((m) => `${normalizeProducerOrCuvee(m.producer)}|${normalizeProducerOrCuvee(m.name)}`));
      expect(keys.size).toBe(1);
      const sizes = new Set(members.map((m) => m.sizeMl));
      expect(sizes.size).toBe(members.length);
    }
  });
});

describe("normalizeProducerOrCuvee (unit, no P1 dependency)", () => {
  it("strips accents and folds case", () => {
    expect(normalizeProducerOrCuvee("Château Belair-Vauban")).toBe(normalizeProducerOrCuvee("Chateau Belair-Vauban"));
  });

  it("folds œ/æ ligatures by hand (NFKD alone does not decompose them)", () => {
    expect(normalizeProducerOrCuvee("Cœur d'Alsace")).toBe(normalizeProducerOrCuvee("Coeur d'Alsace"));
  });

  it("is word-order invariant via token sort", () => {
    expect(normalizeProducerOrCuvee("Domaine Jean Grivot")).toBe(normalizeProducerOrCuvee("Jean Grivot Domaine"));
  });

  it("does NOT treat two genuinely different producers as equal", () => {
    expect(normalizeProducerOrCuvee("Domaine Jean Grivot")).not.toBe(normalizeProducerOrCuvee("Domaine Anne Gros"));
  });

  // D3 (round-2 critic finding): a possessive apostrophe and a pair of
  // period-separated initials used to both decay to stray single-character
  // tokens ("brien"+"s" vs "o"+"s"), producing an IDENTICAL sorted token
  // multiset for two plausibly different producers.
  it("does NOT collapse a possessive apostrophe and period-separated initials into the same key (D3)", () => {
    expect(normalizeProducerOrCuvee("O'Brien's Vineyard")).not.toBe(normalizeProducerOrCuvee("O.S. Brien Vineyard"));
  });

  it("still folds a name-internal apostrophe exactly as before (byte-for-byte parity with P1's frozen normalizeForDedup)", () => {
    // Cœur d'Alsace / Coeur d'Alsace is P1's own punctuation_spacing golden
    // vector (generate-partner-cellar.mjs SPELLING_SEEDS). The D3 fix must
    // NOT touch this apostrophe position — only a trailing possessive "'s".
    expect(normalizeProducerOrCuvee("Cœur d'Alsace")).toBe(normalizeProducerOrCuvee("Coeur d'Alsace"));
  });
});

describe("normalizeVintage / isNvVintageText (unit, no P1 dependency)", () => {
  it("returns null for empty/null input", () => {
    expect(normalizeVintage(null)).toBeNull();
    expect(normalizeVintage("")).toBeNull();
    expect(normalizeVintage("   ")).toBeNull();
  });

  it("accepts the closed NV allowlist, case/spacing/punctuation-insensitive", () => {
    for (const text of ["NV", "nv", "N V", "n.v.", "non vintage", "NONVINTAGE", "MV", "multi-vintage"]) {
      expect(isNvVintageText(text)).toBe(true);
      expect(normalizeVintage(text)).toBeNull();
    }
  });

  it("still accepts a valid numeric vintage", () => {
    expect(normalizeVintage("2018")).toBe(2018);
  });

  it("still rejects garbage text that merely resembles NV-adjacent noise", () => {
    for (const text of ["N/A", "unknown", "TBD"]) {
      expect(isNvVintageText(text)).toBe(false);
      expect(() => normalizeVintage(text)).toThrow();
    }
  });

  it("C18: rejects a numeric prefix with trailing garbage instead of silently truncating it", () => {
    for (const text of ["2015abc", "2015.0", "2015 2016", "+2015", "2,015"]) {
      expect(() => normalizeVintage(text)).toThrow();
    }
  });

  it("rejects an out-of-range year", () => {
    expect(() => normalizeVintage("1899")).toThrow();
    expect(() => normalizeVintage(String(CURRENT_YEAR_PLUS_TWO()))).toThrow();
  });
});

function CURRENT_YEAR_PLUS_TWO(): number {
  return new Date().getFullYear() + 2;
}



// P2 round-4 (D8): the PRIMARY, unconditional contract enforcement — runs
// on every machine, in CI, forever, with zero dependency on the P1
// sibling worktree. Asserts P2's live functions against the frozen
// snapshot in __fixtures__/normalization-golden-vectors.json.
describe("normalization golden vectors (frozen, no sibling dependency — always runs)", () => {
  it("normalizeProducerOrCuvee matches every frozen producer/cuvee vector", () => {
    expect(goldenVectors.producerOrCuveeVectors.length).toBeGreaterThan(0);
    const mismatches: string[] = [];
    for (const { input, expected } of goldenVectors.producerOrCuveeVectors) {
      const actual = normalizeProducerOrCuvee(input);
      if (actual !== expected) {
        mismatches.push(`"${input}" -> expected "${expected}", got "${actual}"`);
      }
    }
    expect(mismatches.join("\n")).toBe("");
  });

  it("normalizeVintage/isNvVintageText match every frozen vintage-text vector", () => {
    expect(goldenVectors.vintageTextVectors.length).toBeGreaterThan(0);
    const mismatches: string[] = [];
    for (const { input, expectedIsNv, outcome } of goldenVectors.vintageTextVectors) {
      const actualIsNv = isNvVintageText(input);
      if (actualIsNv !== expectedIsNv) {
        mismatches.push(`isNvVintageText("${input}") -> expected ${expectedIsNv}, got ${actualIsNv}`);
      }
      if (outcome === "throws") {
        try {
          normalizeVintage(input);
          mismatches.push(`normalizeVintage("${input}") -> expected to throw, did not`);
        } catch {
          // expected
        }
      } else {
        let actual: number | null | "threw";
        try {
          actual = normalizeVintage(input);
        } catch {
          actual = "threw";
        }
        if (actual !== outcome) {
          mismatches.push(`normalizeVintage("${input}") -> expected ${JSON.stringify(outcome)}, got ${JSON.stringify(actual)}`);
        }
      }
    }
    expect(mismatches.join("\n")).toBe("");
  });
});

// P2 ROUND-6 (D9-residual #2): THE THIRD PARTY TO THIS CONTRACT.
//
// Until round 5 the SQL side only ever COMPARED, so its divergence from
// this file was cosmetic and its worst case was a false negative — 0101's
// header said exactly that, and was right at the time. Round 5 moved
// identity-key derivation server-side and round 6 made
// canonical_wines.producer_norm/cuvee_norm STORED GENERATED columns
// computed by public.identity_normalize_text(). The SQL function is now
// the definition of the identity key, so a divergence between it and
// normalizeProducerOrCuvee is a false POSITIVE — two genuinely different
// wines sharing one canonical row, the single failure the blueprint cares
// about most.
//
// That is not hypothetical. When the derivation moved, the SQL function
// had no counterpart to this file's possessive-suffix rule, so
// "O'Brien's Vineyard" and "O.S. Brien Vineyard" — the exact D3 pair
// round 2 separated — both normalized to "brien o s vineyard". Measured
// against the frozen vectors: 10 of 17 agreed before the rule was ported
// into SQL, 17 of 17 after, and every one of the 7 failures was that one
// cause.
//
// This block runs the SAME frozen vectors through the LIVE database
// function. It needs a live stack, so unlike the frozen block above it
// cannot be unconditional — which is precisely why the possessive rule is
// ALSO pinned by supabase/tests/0099_resolve_wine_variants_bulk.sql's D3
// case, which drives the real RPC and always runs under `supabase test
// db`. Two independent guards, because a skipped test protects nothing
// (D8's own lesson).
describe.skipIf(!hasLiveDb)("SQL identity_normalize_text parity with normalizeProducerOrCuvee (live DB)", () => {
  it("the database function matches the frozen contract for every producer/cuvee vector", async () => {
    const vectors = goldenVectors.producerOrCuveeVectors;
    expect(vectors.length).toBeGreaterThan(0);

    const admin = createClient(supabaseUrl!, serviceRoleKey!, { auth: { persistSession: false } });
    const mismatches: string[] = [];
    for (const { input, expected } of vectors) {
      const { data, error } = await admin.rpc("identity_normalize_text", { raw: input } as never);
      if (error) throw new Error(`identity_normalize_text("${input}") failed: ${error.message}`);
      if (data !== expected) {
        mismatches.push(`SQL identity_normalize_text("${input}") -> expected "${expected}", got "${String(data)}"`);
      }
      // Belt and braces: the TS side must agree with the same frozen
      // value, so this test fails loudly if the two implementations drift
      // in EITHER direction rather than only when SQL moves.
      const ts = normalizeProducerOrCuvee(input);
      if (ts !== data) {
        mismatches.push(`TS/SQL disagree on "${input}": TS "${ts}" vs SQL "${String(data)}"`);
      }
    }
    expect(mismatches.join("\n")).toBe("");
  });
});

// P2 round-3 (D3-residual), upgraded round-4 (D8): ADDITIONAL protection
// while the P1 sibling worktree exists — checks P1's LIVE function
// against the SAME frozen golden file (not just against P2's live
// output), so a future edit on either side that drifts from the frozen
// contract still fails immediately. This is what originally caught the
// round-2 divergence ("O'Brien's Vineyard" et al.), and P1's lane has
// since adopted the byte-identical possessive rule (commit c537d84's
// regex, same pipeline position) — this now passes because both sides
// genuinely agree, not because the check is weak.
describe.skipIf(!hasP1Fixture)("live P1/P2 normalization parity (additional guard while both worktrees exist)", () => {
  it("P1's live normalizeForDedup agrees with the frozen expected value for every golden producer/cuvee vector", async () => {
    const mod = (await import(p1FixturePath)) as P1Module;
    const mismatches: string[] = [];
    for (const { input, expected } of goldenVectors.producerOrCuveeVectors) {
      const p1Result = mod.normalizeForDedup(input);
      if (p1Result !== expected) {
        mismatches.push(`"${input}" -> frozen: "${expected}"  P1 live: "${p1Result}"`);
      }
    }
    expect(mismatches.join("\n")).toBe("");
  });
});
