"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { readApiError } from "@/lib/api/client-error";
import {
  createIdempotentCommandStore,
  createSessionCommandPersistence,
  readApiErrorCode,
  shouldRetainIdempotencyKey,
} from "@/lib/api/idempotency-client";
import { useFocusTrap } from "@/lib/hooks/use-focus-trap";

interface QrCodeProps {
  url: string;
}

function QrCode({ url }: QrCodeProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    import("qrcode").then((QRCode) => {
      QRCode.toString(url, {
        type: "svg",
        margin: 1,
        color: { dark: "#1A1A1A", light: "#00000000" },
      }).then((svg) => {
        // Safe: SVG is generated by the qrcode library from a URL we control
        if (containerRef.current) containerRef.current.replaceChildren();
        const parser = new DOMParser();
        const doc = parser.parseFromString(svg, "image/svg+xml");
        const svgEl = doc.documentElement;
        if (containerRef.current) containerRef.current.appendChild(svgEl);
      });
    });
  }, [url]);

  return <div ref={containerRef} className="mx-auto w-[200px]" role="img" aria-label={`QR code linking to ${url}`} />;
}

interface PublishModalProps {
  listId: string;
  currentSlug: string | null;
  isPublished: boolean;
  onClose: () => void;
}

export function PublishModal({ listId, currentSlug, isPublished, onClose }: PublishModalProps) {
  const router = useRouter();
  const [wineListCommands] = useState(() =>
    createIdempotentCommandStore({
      persistence: createSessionCommandPersistence(
        "terroir:wine-list-publish-modal",
      ),
    }),
  );
  const [publishing, setPublishing] = useState(false);
  const [slug, setSlug] = useState(currentSlug ?? "");
  const [slugInput, setSlugInput] = useState(currentSlug ?? "");
  const [slugError, setSlugError] = useState<string | null>(null);
  const [slugSuccess, setSlugSuccess] = useState(false);
  const [published, setPublished] = useState(isPublished);
  const [copied, setCopied] = useState(false);
  const trapRef = useRef<HTMLDivElement>(null);
  const slugMutationRef = useRef(false);
  const publicationMutationRef = useRef(false);
  const publicationReconciliationRef = useRef<
    "publish" | "unpublish" | null
  >(null);
  useFocusTrap({ containerRef: trapRef, onEscape: onClose });

  useEffect(() => {
    const reconciliation = publicationReconciliationRef.current;
    if (publicationMutationRef.current) return;
    const confirmedAction = isPublished ? "publish" : "unpublish";
    if (!reconciliation) {
      try {
        wineListCommands.abandon(
          `wine-list:${listId}:${confirmedAction}`,
        );
      } catch {
        // A live command owns its key until it settles.
      }
      return;
    }
    const isReconciled =
      (reconciliation === "publish" && isPublished) ||
      (reconciliation === "unpublish" && !isPublished);
    if (!isReconciled) return;
    try {
      wineListCommands.abandon(
        `wine-list:${listId}:${reconciliation}`,
      );
      publicationReconciliationRef.current = null;
    } catch {
      // Keep the retry identity until the in-flight command fully settles.
    }
    const nextSlug = currentSlug ?? "";
    setPublished(isPublished);
    setSlug(nextSlug);
    setSlugInput(nextSlug);
  }, [
    currentSlug,
    isPublished,
    listId,
    publishing,
    wineListCommands,
  ]);

  const publicUrl = slug
    ? `${typeof window !== "undefined" ? window.location.origin : ""}/list/${slug}`
    : null;

  const publish = useCallback(async () => {
    if (publicationMutationRef.current) return;
    publicationMutationRef.current = true;
    setPublishing(true);
    setSlugError(null);
    let responseReceived = false;
    try {
      const body: Record<string, string> = {};
      const trimmed = slugInput.trim().toLowerCase();
      if (trimmed) body.slug = trimmed;

      const { response, data } = await wineListCommands.json<unknown>({
        slot: `wine-list:${listId}:publish`,
        url: `/api/wine-lists/${listId}/publish`,
        method: "POST",
        json: body,
      });
      responseReceived = true;
      if (!response.ok) {
        const shouldReconcile = shouldRetainIdempotencyKey(
          response.status,
          readApiErrorCode(data),
        );
        if (shouldReconcile) {
          publicationReconciliationRef.current = "publish";
          router.refresh();
        } else {
          publicationReconciliationRef.current = null;
        }
        throw new Error(readApiError(data, "Publish failed.").message);
      }
      const nextSlug =
        typeof data === "object" &&
        data !== null &&
        typeof (data as { slug?: unknown }).slug === "string"
          ? (data as { slug: string }).slug
          : null;
      if (!nextSlug) {
        publicationReconciliationRef.current = null;
        router.refresh();
        throw new Error("The server returned an invalid publication.");
      }
      publicationReconciliationRef.current = null;
      setSlug(nextSlug);
      setSlugInput(nextSlug);
      setPublished(true);
      router.refresh();
    } catch (error) {
      if (!responseReceived) {
        publicationReconciliationRef.current = "publish";
        router.refresh();
      }
      setSlugError(
        error instanceof Error && error.message
          ? error.message
          : "Publish failed. Please try again.",
      );
    } finally {
      publicationMutationRef.current = false;
      setPublishing(false);
    }
  }, [listId, router, slugInput, wineListCommands]);

  const unpublish = useCallback(async () => {
    if (publicationMutationRef.current) return;
    publicationMutationRef.current = true;
    setPublishing(true);
    setSlugError(null);
    let responseReceived = false;
    try {
      const { response, data } = await wineListCommands.json<unknown>({
        slot: `wine-list:${listId}:unpublish`,
        url: `/api/wine-lists/${listId}/publish`,
        method: "DELETE",
      });
      responseReceived = true;
      if (!response.ok) {
        const shouldReconcile = shouldRetainIdempotencyKey(
          response.status,
          readApiErrorCode(data),
        );
        if (shouldReconcile) {
          publicationReconciliationRef.current = "unpublish";
          router.refresh();
        } else {
          publicationReconciliationRef.current = null;
        }
        throw new Error(readApiError(data, "Unpublish failed.").message);
      }
      if (
        typeof data !== "object" ||
        data === null ||
        (data as { ok?: unknown }).ok !== true
      ) {
        publicationReconciliationRef.current = null;
        router.refresh();
        throw new Error("The server returned an invalid unpublish response.");
      }
      publicationReconciliationRef.current = null;
      setPublished(false);
      setSlug("");
      setSlugInput("");
      router.refresh();
    } catch (error) {
      if (!responseReceived) {
        publicationReconciliationRef.current = "unpublish";
        router.refresh();
      }
      setSlugError(
        error instanceof Error && error.message
          ? error.message
          : "Unpublish failed. Please try again.",
      );
    } finally {
      publicationMutationRef.current = false;
      setPublishing(false);
    }
  }, [listId, router, wineListCommands]);

  const saveSlug = useCallback(async () => {
    if (slugMutationRef.current) return;
    const trimmed = slugInput.trim().toLowerCase();
    if (!trimmed) {
      setSlugError("Slug must not be empty.");
      return;
    }
    if (trimmed === slug) {
      setSlugError(null);
      return;
    }
    slugMutationRef.current = true;
    setPublishing(true);
    setSlugError(null);
    setSlugSuccess(false);
    const slot = `wine-list:${listId}:slug`;
    try {
      const { response, data } =
        await wineListCommands.json<unknown>({
          slot,
          url: `/api/wine-lists/${listId}`,
          method: "PATCH",
          json: { slug: trimmed },
        });
      if (
        response.ok &&
        typeof data === "object" &&
        data !== null &&
        (data as { ok?: unknown }).ok === true
      ) {
        setSlug(trimmed);
        setSlugSuccess(true);
        setTimeout(() => setSlugSuccess(false), 2000);
      } else {
        setSlugError(readApiError(data, "Failed to update slug.").message);
      }
    } catch (error) {
      setSlugError(
        error instanceof Error && error.message
          ? error.message
          : "Failed to update slug. Please try again.",
      );
    } finally {
      slugMutationRef.current = false;
      setPublishing(false);
    }
  }, [listId, slugInput, slug, wineListCommands]);

  const copyUrl = () => {
    if (!publicUrl) return;
    navigator.clipboard.writeText(publicUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadQr = useCallback(async () => {
    if (!publicUrl || !slug) return;
    // PNG (not the inline SVG) so non-technical users can drop it straight
    // into print templates. White background required — the displayed QR
    // uses a transparent background which won't render on light table tents.
    const QRCode = await import("qrcode");
    const dataUrl = await QRCode.toDataURL(publicUrl, {
      margin: 2,
      width: 1024,
      color: { dark: "#1A1A1A", light: "#FFFFFF" },
    });
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `wine-list-${slug}-qr.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }, [publicUrl, slug]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 px-md"
      role="dialog"
      aria-modal="true"
      aria-labelledby="publish-title"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div ref={trapRef} className="w-full max-w-[420px] rounded-md border border-border bg-surface p-lg shadow-lg">
        {!published ? (
          <>
            <h2 id="publish-title" className="font-serif text-[22px] text-ink">
              Publish wine list
            </h2>
            <p className="mt-xs text-[13px] text-ink-muted">
              This will create a public page anyone can view. You can unpublish
              at any time.
            </p>

            {/* Slug input */}
            <div className="mt-md">
              <label htmlFor="publish-slug" className="block text-[13px] font-medium text-ink">
                Public URL slug
              </label>
              <p className="mt-0.5 text-[12px] text-ink-muted">
                Leave blank to auto-generate from your restaurant name.
              </p>
              <div className="mt-sm flex items-center gap-0 rounded-sm border border-border bg-white">
                <span className="pl-sm text-[13px] text-ink-muted select-none">/list/</span>
                <input
                  id="publish-slug"
                  type="text"
                  value={slugInput}
                  onChange={(e) => {
                    setSlugInput(e.target.value);
                    setSlugError(null);
                  }}
                  placeholder="spring-2026"
                  className="flex-1 h-[38px] bg-transparent px-0 text-[14px] text-ink placeholder:text-ink-muted/50 focus:outline-none"
                  autoComplete="off"
                  spellCheck={false}
                />
              </div>
              {slugError && (
                <p className="mt-xs text-[12px] text-red" role="alert">
                  {slugError}
                </p>
              )}
            </div>

            <div className="mt-lg flex justify-end gap-sm">
              <button
                type="button"
                onClick={onClose}
                className="h-[38px] rounded-sm border border-border-strong px-md text-[14px] font-medium text-ink hover:bg-surface-muted"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={publish}
                disabled={publishing}
                className="h-[38px] rounded-sm bg-accent px-md text-[14px] font-medium text-white hover:bg-accent-hover disabled:opacity-60"
              >
                {publishing ? "Publishing..." : "Publish"}
              </button>
            </div>
          </>
        ) : (
          <>
            <h2 id="publish-title" className="font-serif text-[22px] text-ink">
              Your wine list is live
            </h2>

            {publicUrl && (
              <div className="mt-lg">
                <QrCode url={publicUrl} />
              </div>
            )}

            {publicUrl && (
              <div className="mt-lg">
                <div className="flex items-center gap-sm rounded-sm border border-border bg-surface-muted px-sm py-xs">
                  <span className="min-w-0 flex-1 truncate font-mono text-[12px] text-ink-muted">
                    {publicUrl}
                  </span>
                  <button
                    type="button"
                    onClick={copyUrl}
                    className="shrink-0 rounded-sm px-sm py-xs text-[12px] font-medium text-accent hover:bg-accent-soft"
                  >
                    {copied ? "Copied!" : "Copy"}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={downloadQr}
                  className="mt-sm inline-flex h-[32px] items-center rounded-sm border border-border-strong bg-white px-sm text-[12px] font-medium text-ink hover:bg-surface-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-soft"
                >
                  Download QR (PNG)
                </button>
              </div>
            )}

            {/* Slug editing for published lists */}
            <div className="mt-md">
              <label htmlFor="edit-slug" className="block text-[13px] font-medium text-ink">
                Slug
              </label>
              <div className="mt-sm flex items-center gap-sm">
                <div className="flex flex-1 items-center gap-0 rounded-sm border border-border bg-white">
                  <span className="pl-sm text-[13px] text-ink-muted select-none">/list/</span>
                  <input
                    id="edit-slug"
                    type="text"
                    value={slugInput}
                    onChange={(e) => {
                      setSlugInput(e.target.value);
                      setSlugError(null);
                      setSlugSuccess(false);
                    }}
                    className="flex-1 h-[38px] bg-transparent px-0 text-[14px] text-ink focus:outline-none"
                    autoComplete="off"
                    spellCheck={false}
                  />
                </div>
                <button
                  type="button"
                  onClick={saveSlug}
                  disabled={publishing || slugInput.trim().toLowerCase() === slug}
                  className="h-[38px] shrink-0 rounded-sm border border-border-strong px-md text-[13px] font-medium text-ink hover:bg-surface-muted disabled:opacity-40"
                >
                  {publishing ? "..." : "Save"}
                </button>
              </div>
              {slugError && (
                <p className="mt-xs text-[12px] text-red" role="alert">
                  {slugError}
                </p>
              )}
              {slugSuccess && (
                <p className="mt-xs text-[12px] text-green-600">
                  Slug updated.
                </p>
              )}
            </div>

            <div className="mt-lg flex justify-between items-center">
              {publicUrl && (
                <a
                  href={publicUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[13px] font-medium text-accent hover:underline"
                >
                  Open in new tab
                </a>
              )}
              <div className="flex gap-sm">
                <button
                  type="button"
                  onClick={unpublish}
                  disabled={publishing}
                  className="h-[38px] rounded-sm border border-border-strong px-md text-[14px] font-medium text-ink hover:bg-surface-muted disabled:opacity-60"
                >
                  {publishing ? "Unpublishing..." : "Unpublish"}
                </button>
                <button
                  type="button"
                  onClick={onClose}
                  className="h-[38px] rounded-sm bg-accent px-md text-[14px] font-medium text-white hover:bg-accent-hover"
                >
                  Done
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
