"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useFocusTrap } from "@/lib/hooks/use-focus-trap";

interface QrCodeProps {
  url: string;
}

function QrCode({ url }: QrCodeProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    import("qrcode").then((QRCode) => {
      QRCode.toString(url, {
        type: "svg",
        margin: 1,
        color: { dark: "#1A1A1A", light: "#00000000" },
      }).then((svg) => {
        // Safe: SVG is generated by the qrcode library from a URL we control
        if (containerRef.current) containerRef.current.replaceChildren();
        const parser = new DOMParser();
        const doc = parser.parseFromString(svg, "image/svg+xml");
        const svgEl = doc.documentElement;
        if (containerRef.current) containerRef.current.appendChild(svgEl);
      });
    });
  }, [url]);

  return <div ref={containerRef} className="mx-auto w-[200px]" role="img" aria-label={`QR code linking to ${url}`} />;
}

interface PublishModalProps {
  listId: string;
  currentSlug: string | null;
  isPublished: boolean;
  onClose: () => void;
}

export function PublishModal({ listId, currentSlug, isPublished, onClose }: PublishModalProps) {
  const [publishing, setPublishing] = useState(false);
  const [slug, setSlug] = useState(currentSlug ?? "");
  const [slugInput, setSlugInput] = useState(currentSlug ?? "");
  const [slugError, setSlugError] = useState<string | null>(null);
  const [slugSuccess, setSlugSuccess] = useState(false);
  const [published, setPublished] = useState(isPublished);
  const [copied, setCopied] = useState(false);
  const trapRef = useRef<HTMLDivElement>(null);
  useFocusTrap({ containerRef: trapRef, onEscape: onClose });

  const publicUrl = slug
    ? `${typeof window !== "undefined" ? window.location.origin : ""}/list/${slug}`
    : null;

  const publish = useCallback(async () => {
    setPublishing(true);
    setSlugError(null);
    try {
      const body: Record<string, string> = {};
      const trimmed = slugInput.trim().toLowerCase();
      if (trimmed) body.slug = trimmed;

      const res = await fetch(`/api/wine-lists/${listId}/publish`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (res.ok) {
        setSlug((data as { slug: string }).slug);
        setSlugInput((data as { slug: string }).slug);
        setPublished(true);
      } else {
        setSlugError((data as { error?: string }).error ?? "Publish failed.");
      }
    } finally {
      setPublishing(false);
    }
  }, [listId, slugInput]);

  const unpublish = useCallback(async () => {
    setPublishing(true);
    try {
      const res = await fetch(`/api/wine-lists/${listId}/publish`, {
        method: "DELETE",
      });
      if (res.ok) {
        setPublished(false);
        setSlug("");
        setSlugInput("");
      }
    } finally {
      setPublishing(false);
    }
  }, [listId]);

  const saveSlug = useCallback(async () => {
    const trimmed = slugInput.trim().toLowerCase();
    if (!trimmed) {
      setSlugError("Slug must not be empty.");
      return;
    }
    if (trimmed === slug) {
      setSlugError(null);
      return;
    }
    setPublishing(true);
    setSlugError(null);
    setSlugSuccess(false);
    try {
      const res = await fetch(`/api/wine-lists/${listId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ slug: trimmed }),
      });
      if (res.ok) {
        setSlug(trimmed);
        setSlugSuccess(true);
        setTimeout(() => setSlugSuccess(false), 2000);
      } else {
        const data = await res.json();
        setSlugError((data as { error?: string }).error ?? "Failed to update slug.");
      }
    } finally {
      setPublishing(false);
    }
  }, [listId, slugInput, slug]);

  const copyUrl = () => {
    if (!publicUrl) return;
    navigator.clipboard.writeText(publicUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadQr = useCallback(async () => {
    if (!publicUrl || !slug) return;
    // PNG (not the inline SVG) so non-technical users can drop it straight
    // into print templates. White background required — the displayed QR
    // uses a transparent background which won't render on light table tents.
    const QRCode = await import("qrcode");
    const dataUrl = await QRCode.toDataURL(publicUrl, {
      margin: 2,
      width: 1024,
      color: { dark: "#1A1A1A", light: "#FFFFFF" },
    });
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `wine-list-${slug}-qr.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }, [publicUrl, slug]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 px-md"
      role="dialog"
      aria-modal="true"
      aria-labelledby="publish-title"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div ref={trapRef} className="w-full max-w-[420px] rounded-card border border-hairline bg-canvas p-lg">
        {!published ? (
          <>
            <h2 id="publish-title" className="font-serif text-[22px] text-ink">
              Publish wine list
            </h2>
            <p className="mt-xs text-[13px] text-ink-muted">
              This will create a public page anyone can view. You can unpublish
              at any time.
            </p>

            {/* Slug input */}
            <div className="mt-md">
              <label htmlFor="publish-slug" className="block text-[13px] font-medium text-ink">
                Public URL slug
              </label>
              <p className="mt-0.5 text-[12px] text-ink-muted">
                Leave blank to auto-generate from your restaurant name.
              </p>
              <div className="mt-sm flex items-center gap-0 rounded-pill border border-hairline bg-white">
                <span className="pl-md text-[13px] text-ink-muted select-none">/list/</span>
                <input
                  id="publish-slug"
                  type="text"
                  value={slugInput}
                  onChange={(e) => {
                    setSlugInput(e.target.value);
                    setSlugError(null);
                  }}
                  placeholder="spring-2026"
                  className="flex-1 h-[38px] bg-transparent px-0 pr-md text-[14px] text-ink placeholder:text-ink-muted/50 focus:outline-none"
                  autoComplete="off"
                  spellCheck={false}
                />
              </div>
              {slugError && (
                <p className="mt-xs text-[12px] text-primary" role="alert">
                  {slugError}
                </p>
              )}
            </div>

            <div className="mt-lg flex justify-end gap-sm">
              <button
                type="button"
                onClick={onClose}
                className="h-[38px] rounded-pill border border-hairline px-md text-[14px] font-medium text-ink hover:bg-bridge-surface"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={publish}
                disabled={publishing}
                className="h-[38px] rounded-pill bg-primary px-md text-[14px] font-medium text-white hover:bg-primary-hover disabled:opacity-60"
              >
                {publishing ? "Publishing..." : "Publish"}
              </button>
            </div>
          </>
        ) : (
          <>
            <h2 id="publish-title" className="font-serif text-[22px] text-ink">
              Your wine list is live
            </h2>

            {publicUrl && (
              <div className="mt-lg">
                <QrCode url={publicUrl} />
              </div>
            )}

            {publicUrl && (
              <div className="mt-lg">
                <div className="flex items-center gap-sm rounded-pill border border-hairline bg-bridge-surface px-md py-xs">
                  <span className="min-w-0 flex-1 truncate font-mono text-[12px] text-ink-muted">
                    {publicUrl}
                  </span>
                  <button
                    type="button"
                    onClick={copyUrl}
                    className="shrink-0 rounded-pill px-sm py-xs text-[12px] font-medium text-primary hover:bg-blush-wash"
                  >
                    {copied ? "Copied!" : "Copy"}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={downloadQr}
                  className="mt-sm inline-flex h-[32px] items-center rounded-pill border border-hairline bg-white px-sm text-[12px] font-medium text-ink hover:bg-bridge-surface focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-soft"
                >
                  Download QR (PNG)
                </button>
              </div>
            )}

            {/* Slug editing for published lists */}
            <div className="mt-md">
              <label htmlFor="edit-slug" className="block text-[13px] font-medium text-ink">
                Slug
              </label>
              <div className="mt-sm flex items-center gap-sm">
                <div className="flex flex-1 items-center gap-0 rounded-pill border border-hairline bg-white">
                  <span className="pl-md text-[13px] text-ink-muted select-none">/list/</span>
                  <input
                    id="edit-slug"
                    type="text"
                    value={slugInput}
                    onChange={(e) => {
                      setSlugInput(e.target.value);
                      setSlugError(null);
                      setSlugSuccess(false);
                    }}
                    className="flex-1 h-[38px] bg-transparent px-0 pr-md text-[14px] text-ink focus:outline-none"
                    autoComplete="off"
                    spellCheck={false}
                  />
                </div>
                <button
                  type="button"
                  onClick={saveSlug}
                  disabled={publishing || slugInput.trim().toLowerCase() === slug}
                  className="h-[38px] shrink-0 rounded-pill border border-hairline px-md text-[13px] font-medium text-ink hover:bg-bridge-surface disabled:opacity-40"
                >
                  {publishing ? "..." : "Save"}
                </button>
              </div>
              {slugError && (
                <p className="mt-xs text-[12px] text-primary" role="alert">
                  {slugError}
                </p>
              )}
              {slugSuccess && (
                <p className="mt-xs text-[12px] text-sage-ink">
                  Slug updated.
                </p>
              )}
            </div>

            <div className="mt-lg flex justify-between items-center">
              <a
                href={publicUrl ?? "#"}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[13px] font-medium text-primary hover:underline"
              >
                Open in new tab
              </a>
              <div className="flex gap-sm">
                <button
                  type="button"
                  onClick={unpublish}
                  disabled={publishing}
                  className="h-[38px] rounded-pill border border-hairline px-md text-[14px] font-medium text-ink hover:bg-bridge-surface disabled:opacity-60"
                >
                  {publishing ? "Unpublishing..." : "Unpublish"}
                </button>
                <button
                  type="button"
                  onClick={onClose}
                  className="h-[38px] rounded-pill bg-primary px-md text-[14px] font-medium text-white hover:bg-primary-hover"
                >
                  Done
                </button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
